### ISSUE TITLE
trouble running the app in docker

### ISSUE THREAD

**Issue by cpg** [mhils/gsoc-eval#3]
hi, in `docker-compose up` i get the following:

```
Creating network "gsoceval_default" with the default driver
Creating gsoceval_gsoc-eval_1
Attaching to gsoceval_gsoc-eval_1
gsoc-eval_1  | npm info it worked if it ends with ok
gsoc-eval_1  | npm info using npm@3.10.10
gsoc-eval_1  | npm info using node@v6.10.2
gsoc-eval_1  | npm info lifecycle gsoc-eval@1.0.0~prestart: gsoc-eval@1.0.0
gsoc-eval_1  |
gsoc-eval_1  | > gsoc-eval@1.0.0 start /usr/src/app
gsoc-eval_1  | > node server.js
gsoc-eval_1  |
gsoc-eval_1  | npm info lifecycle gsoc-eval@1.0.0~start: gsoc-eval@1.0.0
gsoc-eval_1  | module.js:471
gsoc-eval_1  |     throw err;
gsoc-eval_1  |     ^
gsoc-eval_1  |
gsoc-eval_1  | Error: Cannot find module 'express'
gsoc-eval_1  |     at Function.Module._resolveFilename (module.js:469:15)
gsoc-eval_1  |     at Function.Module._load (module.js:417:25)
gsoc-eval_1  |     at Module.require (module.js:497:17)
gsoc-eval_1  |     at require (internal/module.js:20:19)
gsoc-eval_1  |     at Object.<anonymous> (/usr/src/app/server.js:1:77)
gsoc-eval_1  |     at Module._compile (module.js:570:32)
gsoc-eval_1  |     at Object.Module._extensions..js (module.js:579:10)
gsoc-eval_1  |     at Module.load (module.js:487:32)
gsoc-eval_1  |     at tryModuleLoad (module.js:446:12)
gsoc-eval_1  |     at Function.Module._load (module.js:438:3)
gsoc-eval_1  |
gsoc-eval_1  | npm info lifecycle gsoc-eval@1.0.0~start: Failed to exec start script
gsoc-eval_1  | npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
gsoc-eval_1  | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
gsoc-eval_1  | npm ERR! node v6.10.2
gsoc-eval_1  | npm ERR! npm  v3.10.10
gsoc-eval_1  | npm ERR! code ELIFECYCLE
gsoc-eval_1  | npm ERR! gsoc-eval@1.0.0 start: `node server.js`
gsoc-eval_1  | npm ERR! Exit status 1
gsoc-eval_1  | npm ERR!
gsoc-eval_1  | npm ERR! Failed at the gsoc-eval@1.0.0 start script 'node server.js'.
gsoc-eval_1  | npm ERR! Make sure you have the latest version of node.js and npm installed.
gsoc-eval_1  | npm ERR! If you do, this is most likely a problem with the gsoc-eval package,
gsoc-eval_1  | npm ERR! not with npm itself.
gsoc-eval_1  | npm ERR! Tell the author that this fails on your system:
gsoc-eval_1  | npm ERR!     node server.js
gsoc-eval_1  | npm ERR! You can get information on how to open an issue for this project with:
gsoc-eval_1  | npm ERR!     npm bugs gsoc-eval
gsoc-eval_1  | npm ERR! Or if that isn't available, you can get their info via:
gsoc-eval_1  | npm ERR!     npm owner ls gsoc-eval
gsoc-eval_1  | npm ERR! There is likely additional logging output above.
gsoc-eval_1  | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
gsoc-eval_1  |
gsoc-eval_1  | npm ERR! Please include the following file with any support request:
gsoc-eval_1  | npm ERR!     /usr/src/app/npm-debug.log
gsoceval_gsoc-eval_1 exited with code 1
```

**Comment by mhils** [comment]
Hi @cpg,

I just merged a PR from @yukiisbored that fixes the issue you are seeing. The following should work for you now:

```
git pull
docker-compose build
docker-compose up
```

Cheers,
Max

**Comment by cpg** [comment]
Great. Worked well. Now to figure out how to deploy this in the background and connect apache to it.

**Comment by yukiisbored** [comment]
@cpg `docker-compose up -d` also look into reverse proxy in Apache.
